### ISSUE TITLE
App sorting

### ISSUE THREAD

**Issue by spacelordmother** [monome-community/collected#1]
Any chance to get the apps sorted by media (audio, midi, video, etc) as it was on the old monome.org site?  Since some of the names don't necessarily relate to the functionality, it can be hard to find apps for each use.  Thanks!

**Comment by tehn** [comment]
my best suggestion would be to start a new repo with an index.md page
linking to the other projects as a sort of guide. i can get this started if
other people can finish it.

**Comment by jasonw22** [comment]
Here are the apps. I'd be happy to categorize them in some way: 
https://github.com/monome-community/collected/wiki/monome-apps-for-arc-and-grid

**Comment by tehn** [comment]
whoa, this is fantastic! thank you. i'm not completely sure how to approach
a "sorting" so perhaps we should open up the question to the community (as
also an invitation for further contribution)

best,

b
